<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalPelajaranSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('jadwal_pelajaran')->insert([
            [
                'mata_pelajaran' => 'Matematika',
                'ruangan'        => 'A',
                'hari'           => 'Senin',
                'nama_guru'      => 'Budi Santoso',
                'mulai'          => '07:00:00',
                'berakhir'       => '08:30:00',
                'kelas'          => '1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Bahasa Indonesia',
                'ruangan'        => 'B',
                'hari'           => 'Senin',
                'nama_guru'      => 'Siti Aminah',
                'mulai'          => '08:30:00',
                'berakhir'       => '10:00:00',
                'kelas'          => '1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Aqidah',
                'ruangan'        => 'C',
                'hari'           => 'Senin',
                'nama_guru'      => 'Dedi Kurniawan',
                'mulai'          => '10:15:00',
                'berakhir'       => '11:45:00',
                'kelas'          => '1',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Qur\'an Hadis',
                'ruangan'        => 'D',
                'hari'           => 'Selasa',
                'nama_guru'      => 'Eka Putri',
                'mulai'          => '07:00:00',
                'berakhir'       => '08:30:00',
                'kelas'          => '2',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Bahasa Arab',
                'ruangan'        => 'E',
                'hari'           => 'Selasa',
                'nama_guru'      => 'Ahmad Zulfikar',
                'mulai'          => '08:30:00',
                'berakhir'       => '10:00:00',
                'kelas'          => '2',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Fiqih',
                'ruangan'        => 'F',
                'hari'           => 'Rabu',
                'nama_guru'      => 'Rina Wahyuni',
                'mulai'          => '07:00:00',
                'berakhir'       => '08:30:00',
                'kelas'          => '3',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Pendidikan Agama Islam',
                'ruangan'        => 'G',
                'hari'           => 'Rabu',
                'nama_guru'      => 'Hendra Saputra',
                'mulai'          => '08:30:00',
                'berakhir'       => '10:00:00',
                'kelas'          => '3',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Aqidah',
                'ruangan'        => 'H',
                'hari'           => 'Rabu',
                'nama_guru'      => 'Dewi Lestari',
                'mulai'          => '10:15:00',
                'berakhir'       => '11:45:00',
                'kelas'          => '3',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Fiqih',
                'ruangan'        => 'I',
                'hari'           => 'Kamis',
                'nama_guru'      => 'Teguh Prasetyo',
                'mulai'          => '07:00:00',
                'berakhir'       => '08:30:00',
                'kelas'          => '4',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Bahasa Inggris',
                'ruangan'        => 'J',
                'hari'           => 'Kamis',
                'nama_guru'      => 'Linda Handayani',
                'mulai'          => '08:30:00',
                'berakhir'       => '10:00:00',
                'kelas'          => '4',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Pendidikan Jasmani (PJOK)',
                'ruangan'        => 'K',
                'hari'           => 'Kamis',
                'nama_guru'      => 'Agus Wijaya',
                'mulai'          => '10:15:00',
                'berakhir'       => '11:45:00',
                'kelas'          => '4',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Seni Budaya & Keterampilan',
                'ruangan'        => 'L',
                'hari'           => 'Jumat',
                'nama_guru'      => 'Yuniarti',
                'mulai'          => '07:00:00',
                'berakhir'       => '08:30:00',
                'kelas'          => '5',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Matematika',
                'ruangan'        => 'M',
                'hari'           => 'Jumat',
                'nama_guru'      => 'Budi Santoso',
                'mulai'          => '08:30:00',
                'berakhir'       => '10:00:00',
                'kelas'          => '5',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Bahasa Indonesia',
                'ruangan'        => 'N',
                'hari'           => 'Jumat',
                'nama_guru'      => 'Siti Aminah',
                'mulai'          => '10:15:00',
                'berakhir'       => '11:45:00',
                'kelas'          => '5',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Qur\'an Hadis',
                'ruangan'        => 'O',
                'hari'           => 'Senin',
                'nama_guru'      => 'Ust. Fajar',
                'mulai'          => '11:45:00',
                'berakhir'       => '13:15:00',
                'kelas'          => '6',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'mata_pelajaran' => 'Bahasa Arab',
                'ruangan'        => 'P',
                'hari'           => 'Senin',
                'nama_guru'      => 'Ahmad Zulfikar',
                'mulai'          => '13:00:00',
                'berakhir'       => '14:30:00',
                'kelas'          => '6',
                'created_at'     => now(),
                'updated_at'     => now(),
            ]
        ]);
    }
}
